Feature/55655 mattress type app is
MatCron/MatCron pull request #32
Opened 2024-12-02 07:14 UTC by Sanid1707

This PR implements all APIs for Mattress Type :
The Functionality includes the following :

- CRUD functionality 
- Displaying the Type Mattress is split into 2 APIS to avoid over fetching and prevent backend load

2024-12-02 11:14 UTC, Terrie-png requested changes
Can revert the changes from appsetting ?

2024-12-02 11:14 UTC, Terrie-png commented on Backend/Backend/DTOs/MattressType/MattressTypeTileDTO.cs
why create a duplication of dto ?

2024-12-02 11:14 UTC, Terrie-png commented on Backend/Backend/appsettings.json
brother dont change the appsettihng to the main branch i need this for deployment on docker

2024-12-02 11:35 UTC, Sanid1707 commented on Backend/Backend/DTOs/MattressType/MattressTypeTileDTO.cs
To. make the backend scalable and prevent over fetching I have separated the displaying the Mattress Details into 2 APIS and hence there are 2 DTOs to make this process more readable . Each DTO serves a specific purpose, tailored for the data needed by a specific API.

2024-12-18 00:00 UTC, Terrie-png approved these changes, later dismissed
Everything looks fine

2024-12-18 01:38 UTC, Terrie-png approved these changes, later dismissed
Looks good now

2024-12-18 14:49 UTC, Terrie-png approved these changes
ok

2024-12-18 18:52 UTC, merged